<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGHv9vST\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGHv9vST/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGHv9vST.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGHv9vST\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGHv9vST\App_KernelDevDebugContainer([
    'container.build_hash' => 'GHv9vST',
    'container.build_id' => '53c59a87',
    'container.build_time' => 1670938190,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGHv9vST');
