<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerELfgVDx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerELfgVDx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerELfgVDx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerELfgVDx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerELfgVDx\App_KernelDevDebugContainer([
    'container.build_hash' => 'ELfgVDx',
    'container.build_id' => '7bfbcf7f',
    'container.build_time' => 1669132676,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerELfgVDx');
