<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUYFZKxj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUYFZKxj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUYFZKxj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUYFZKxj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUYFZKxj\App_KernelDevDebugContainer([
    'container.build_hash' => 'UYFZKxj',
    'container.build_id' => 'ed45f109',
    'container.build_time' => 1668527116,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUYFZKxj');
